# Generated by Django 3.0.8 on 2020-08-13 01:27

import apps.dht11.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dht11', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dht11',
            name='timestamp',
            field=apps.dht11.models.CustomDateTimeField(auto_now_add=True, verbose_name='thời gian cập nhật'),
        ),
    ]
